export type { PlatformRoute } from './platform.js'
export { PLATFORM } from './platform.js'
export type { RegionalRoute } from './regional.js'
export { REGIONAL } from './regional.js'
export { toRegional } from './routing.js'
